logo: "/1623072774562.png?raw=true" # your photo (or logo) here
title: Raja Christopher S # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Lead Engineer at HCL Technologies Limited, Chennai.<br>
  <br><br>
  <a href="mailto:rajachris27@gmail.com">rajachris27@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/raja-christopher-s-%E2%9C%85-192312100/">LinkedIn Profile</a>
  <br>
  
  <p align='left'>
  <img src="/images.png?raw=true" alt="html" width="200" height="100">
  </p>
theme: jekyll-theme-minimal
